### GET on "/"

GET http://localhost:3000

### POST on "/"

POST http://localhost:3000

{
    "todo" : "Clean The Room"
}

### PUT on "/"

PUT http://localhost:3000
id : 1

{
    "updatedTodo" : "Updated Todo"
}

### DELETE on "/"

DELETE http://localhost:3000
id : 1